### ISSUE TITLE
There is an error with oracle-java8 dependeces

### ISSUE THREAD

**Issue by ekelvin** [goyalzz/Ubuntu-Java-8-Maven-Docker-Image#1]
There is an error with oracle-java8 dependeces
`...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 oracle-java8-installer : Depends: locales but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c echo 'deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' >> /etc/apt/sources.list &&     echo 'deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main' >> /etc/apt/sources.list &&     apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C2518248EEA14886 &&     apt-get update &&     echo oracle-java${JAVA_VER}-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections &&     apt-get install -y --force-yes --no-install-recommends oracle-java${JAVA_VER}-installer oracle-java${JAVA_VER}-set-default &&     apt-get clean &&     rm -rf /var/cache/oracle-jdk${JAVA_VER}-installer' returned a non-zero code: 100`

**Comment by goyalzz** [comment]
Hi ekelvin,

I will update the docker file until you can get pull the running docker from the link below:
https://hub.docker.com/r/goyalzz/ubuntu-java-8-maven-docker-image/

Thanks,

**Comment by goyalzz** [comment]
Hi ekelvin,

You can check the updated docker file.

Thanks,
